import { ReactQueryKeys } from './types';

/**
 * Object Constant that is used to provide as useQuery's key throughout the application.
 * These have to be unique.
 */
export const QUERYKEYS: ReactQueryKeys = {
  appAudienceSetting: 'appAudienceSetting',
  appBookmarkedProducts: 'appBookmarkedProducts',
  appBookmarkedProductsSetting: 'appBookmarkedProductsSetting',
  appCartItems: 'appCartItems',
  appCartItemsOld: 'appCartItemsOld',
  appMainMenu: 'appMainMenu',
  appMe: 'appMe',
  appProductPriceBreak: 'appProductPriceBreak',
  appProductsPriceBreaks: 'appProductsPriceBreaks',
  appRecentlyViewedProducts: 'appRecentlyViewedProducts',
  appRecentlyViewedProductsSetting: 'appRecentlyViewedProductsSetting',
  appRecentySearchedSetting: 'appRecentySearchedSetting',
  appSearchCategories: 'appSearchCategories',
  appSearchProducts: 'appSearchProducts',
  appSiteMenu: 'appSiteMenu',
  cartMergeProducts: 'cartMergeProducts',
  category: 'category',
  categorySubCategories: 'categorySubCategoryPages',
  checkoutOrderTaxAmount: 'checkoutOrderTaxAmount',
  checkoutShippingOptions: 'checkoutShippingOptions',
  compareProducts: 'compareProducts',
  designAccesories: 'designAccesories',
  designAllSpecifications: 'designAllSpecifications',
  designBase: 'designBase',
  designCadenasIdentifier: 'designCadenasIdentifier',
  designConfigurations: 'designConfigurations',
  designKeySpecifications: 'designKeySpecifications',
  designResources: 'designResources',
  globalAttributeGroups: 'globalAttributeGroups',
  globalAttributeTypes: 'globalAttributeTypes',
  globalModels: 'globalModels',
  globalSeries: 'globalSeries',
  homeCategoryPages: 'homeCategoryPages',
  matchEmailToCustomer: 'matchEmailToCustomer',
  modelKeySpecifications: 'modelKeySpecifications',
  modelResources: 'modelResources',
  orderDetail: 'orderDetail',
  orderLineProducts: 'orderLineProducts',
  orderVerifyProducts: 'orderVerifyProducts',
  orders: 'orders',
  productFinderGridViewItems: 'productFinderGridViewItems',
  productFinderLiquidsWithRelativeDensity:
    'productFinderLiquidsWithRelativeDensity',
  productFinderListViewItems: 'productFinderListViewItems',
  productFinderPredictedResults: 'productFinderPredictedResults',
  productFinderResults: 'productFinderResults',
  productFinderTableHierarchy: 'productFinderTableHierarchy',
  productFinderTableViewDesignsForModel:
    'productFinderTableViewDesignsForModel',
  productFinderTableViewProductListItem:
    'productFinderTableViewProductListItem',
  quote: 'quote',
  quoteDetail: 'quoteDetail',
  quoteRequestDetail: 'quoteRequestDetail',
  quoteRequestLineProducts: 'quoteRequestLineProducts',
  quoteRequests: 'quoteRequests',
  recentOrders: 'recentOrders',
  searchVerifyProduct: 'searchVerifyProduct',
  seriesResources: 'seriesResources',
  footerData: 'footerData'
};
